package com.example.uai.design.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.example.uai.data.model.AppColorTheme

fun AppColorTheme.lightScheme(): ColorScheme = when (this) {
    AppColorTheme.TERRACOTTA -> lightColorScheme(
        primary              = Color(0xFFB5533C),
        onPrimary            = Color(0xFFFFFFFF),
        primaryContainer     = Color(0xFFFFDAD0),
        onPrimaryContainer   = Color(0xFF3B0A02),
        secondary            = Color(0xFF77574D),
        onSecondary          = Color(0xFFFFFFFF),
        secondaryContainer   = Color(0xFFFFDDD5),
        onSecondaryContainer = Color(0xFF2C160F),
        background           = Color(0xFFFAF9F7),
        onBackground         = Color(0xFF1C1917),
        surface              = Color(0xFFFAF9F7),
        onSurface            = Color(0xFF1C1917),
        surfaceVariant       = Color(0xFFEDE8E1),
        onSurfaceVariant     = Color(0xFF534540),
        outline              = Color(0xFF857369),
    )
    AppColorTheme.OCEAN -> lightColorScheme(
        primary              = Color(0xFF1765A8),
        onPrimary            = Color(0xFFFFFFFF),
        primaryContainer     = Color(0xFFD1E4FF),
        onPrimaryContainer   = Color(0xFF001D36),
        secondary            = Color(0xFF516B8A),
        onSecondary          = Color(0xFFFFFFFF),
        secondaryContainer   = Color(0xFFD5E3F7),
        onSecondaryContainer = Color(0xFF0C1E2F),
        background           = Color(0xFFF7F9FF),
        onBackground         = Color(0xFF191C20),
        surface              = Color(0xFFF7F9FF),
        onSurface            = Color(0xFF191C20),
        surfaceVariant       = Color(0xFFDDE3EA),
        onSurfaceVariant     = Color(0xFF41474D),
        outline              = Color(0xFF72787E),
    )
    AppColorTheme.FOREST -> lightColorScheme(
        primary              = Color(0xFF2D6A30),
        onPrimary            = Color(0xFFFFFFFF),
        primaryContainer     = Color(0xFFAEEFAA),
        onPrimaryContainer   = Color(0xFF002204),
        secondary            = Color(0xFF4F6647),
        onSecondary          = Color(0xFFFFFFFF),
        secondaryContainer   = Color(0xFFD3EBC6),
        onSecondaryContainer = Color(0xFF0D2108),
        background           = Color(0xFFF5FBF1),
        onBackground         = Color(0xFF191D17),
        surface              = Color(0xFFF5FBF1),
        onSurface            = Color(0xFF191D17),
        surfaceVariant       = Color(0xFFDCE5D5),
        onSurfaceVariant     = Color(0xFF3F4E3A),
        outline              = Color(0xFF6E7D68),
    )
    AppColorTheme.LAVENDER -> lightColorScheme(
        primary              = Color(0xFF6750A4),
        onPrimary            = Color(0xFFFFFFFF),
        primaryContainer     = Color(0xFFEADDFF),
        onPrimaryContainer   = Color(0xFF21005D),
        secondary            = Color(0xFF625B71),
        onSecondary          = Color(0xFFFFFFFF),
        secondaryContainer   = Color(0xFFE8DEF8),
        onSecondaryContainer = Color(0xFF1D192B),
        background           = Color(0xFFFEFBFF),
        onBackground         = Color(0xFF1C1B1F),
        surface              = Color(0xFFFEFBFF),
        onSurface            = Color(0xFF1C1B1F),
        surfaceVariant       = Color(0xFFE7E0EC),
        onSurfaceVariant     = Color(0xFF49454F),
        outline              = Color(0xFF79747E),
    )
    AppColorTheme.SUNSET -> lightColorScheme(
        primary              = Color(0xFFC44B00),
        onPrimary            = Color(0xFFFFFFFF),
        primaryContainer     = Color(0xFFFFDBCC),
        onPrimaryContainer   = Color(0xFF380F00),
        secondary            = Color(0xFF7A5548),
        onSecondary          = Color(0xFFFFFFFF),
        secondaryContainer   = Color(0xFFFFDDD5),
        onSecondaryContainer = Color(0xFF31130A),
        background           = Color(0xFFFFF8F6),
        onBackground         = Color(0xFF201A18),
        surface              = Color(0xFFFFF8F6),
        onSurface            = Color(0xFF201A18),
        surfaceVariant       = Color(0xFFEDE0DB),
        onSurfaceVariant     = Color(0xFF524744),
        outline              = Color(0xFF857370),
    )
    AppColorTheme.MIDNIGHT -> lightColorScheme(
        primary              = Color(0xFF3849AB),
        onPrimary            = Color(0xFFFFFFFF),
        primaryContainer     = Color(0xFFDDE1FF),
        onPrimaryContainer   = Color(0xFF00106A),
        secondary            = Color(0xFF575E7E),
        onSecondary          = Color(0xFFFFFFFF),
        secondaryContainer   = Color(0xFFDDE0FF),
        onSecondaryContainer = Color(0xFF121B36),
        background           = Color(0xFFFAF8FF),
        onBackground         = Color(0xFF1A1B27),
        surface              = Color(0xFFFAF8FF),
        onSurface            = Color(0xFF1A1B27),
        surfaceVariant       = Color(0xFFE3E1F5),
        onSurfaceVariant     = Color(0xFF46464F),
        outline              = Color(0xFF777590),
    )
}

fun AppColorTheme.darkScheme(): ColorScheme = when (this) {
    AppColorTheme.TERRACOTTA -> darkColorScheme(
        primary              = Color(0xFFFFB59D),
        onPrimary            = Color(0xFF5B1608),
        primaryContainer     = Color(0xFF8E3B27),
        onPrimaryContainer   = Color(0xFFFFDAD0),
        secondary            = Color(0xFFE7BDB3),
        onSecondary          = Color(0xFF442922),
        secondaryContainer   = Color(0xFF5D3F37),
        onSecondaryContainer = Color(0xFFFFDDD5),
        background           = Color(0xFF1C1917),
        onBackground         = Color(0xFFEDE0DC),
        surface              = Color(0xFF1C1917),
        onSurface            = Color(0xFFEDE0DC),
        surfaceVariant       = Color(0xFF534540),
        onSurfaceVariant     = Color(0xFFD8C2BB),
        outline              = Color(0xFFA08C86),
    )
    AppColorTheme.OCEAN -> darkColorScheme(
        primary              = Color(0xFFA3C9F8),
        onPrimary            = Color(0xFF00325A),
        primaryContainer     = Color(0xFF1E4C7F),
        onPrimaryContainer   = Color(0xFFD1E4FF),
        secondary            = Color(0xFFABC7E5),
        onSecondary          = Color(0xFF1B3249),
        secondaryContainer   = Color(0xFF2D4A63),
        onSecondaryContainer = Color(0xFFD5E3F7),
        background           = Color(0xFF191C20),
        onBackground         = Color(0xFFE2E2E9),
        surface              = Color(0xFF191C20),
        onSurface            = Color(0xFFE2E2E9),
        surfaceVariant       = Color(0xFF41474D),
        onSurfaceVariant     = Color(0xFFC1C7CE),
        outline              = Color(0xFF8B9197),
    )
    AppColorTheme.FOREST -> darkColorScheme(
        primary              = Color(0xFF93D48A),
        onPrimary            = Color(0xFF003909),
        primaryContainer     = Color(0xFF0F5017),
        onPrimaryContainer   = Color(0xFFAEEFAA),
        secondary            = Color(0xFFB6CEAC),
        onSecondary          = Color(0xFF223520),
        secondaryContainer   = Color(0xFF384D33),
        onSecondaryContainer = Color(0xFFD3EBC6),
        background           = Color(0xFF191D17),
        onBackground         = Color(0xFFE2E5DD),
        surface              = Color(0xFF191D17),
        onSurface            = Color(0xFFE2E5DD),
        surfaceVariant       = Color(0xFF3E4E39),
        onSurfaceVariant     = Color(0xFFBCC9B5),
        outline              = Color(0xFF87937F),
    )
    AppColorTheme.LAVENDER -> darkColorScheme(
        primary              = Color(0xFFCFBDFE),
        onPrimary            = Color(0xFF381E72),
        primaryContainer     = Color(0xFF4F378B),
        onPrimaryContainer   = Color(0xFFEADDFF),
        secondary            = Color(0xFFCBC2DB),
        onSecondary          = Color(0xFF332D41),
        secondaryContainer   = Color(0xFF4A4458),
        onSecondaryContainer = Color(0xFFE8DEF8),
        background           = Color(0xFF1C1B1F),
        onBackground         = Color(0xFFE6E1E5),
        surface              = Color(0xFF1C1B1F),
        onSurface            = Color(0xFFE6E1E5),
        surfaceVariant       = Color(0xFF49454F),
        onSurfaceVariant     = Color(0xFFCAC4D0),
        outline              = Color(0xFF938F99),
    )
    AppColorTheme.SUNSET -> darkColorScheme(
        primary              = Color(0xFFFFB68A),
        onPrimary            = Color(0xFF5C1900),
        primaryContainer     = Color(0xFF852400),
        onPrimaryContainer   = Color(0xFFFFDBCC),
        secondary            = Color(0xFFEFBDB0),
        onSecondary          = Color(0xFF4B2519),
        secondaryContainer   = Color(0xFF633B2E),
        onSecondaryContainer = Color(0xFFFFDDD5),
        background           = Color(0xFF201A18),
        onBackground         = Color(0xFFEDE0DC),
        surface              = Color(0xFF201A18),
        onSurface            = Color(0xFFEDE0DC),
        surfaceVariant       = Color(0xFF524744),
        onSurfaceVariant     = Color(0xFFD7C2BB),
        outline              = Color(0xFFA0897E),
    )
    AppColorTheme.MIDNIGHT -> darkColorScheme(
        primary              = Color(0xFFBBC3FF),
        onPrimary            = Color(0xFF071778),
        primaryContainer     = Color(0xFF202F93),
        onPrimaryContainer   = Color(0xFFDDE1FF),
        secondary            = Color(0xFFC0C5E4),
        onSecondary          = Color(0xFF2A3054),
        secondaryContainer   = Color(0xFF40476C),
        onSecondaryContainer = Color(0xFFDDE0FF),
        background           = Color(0xFF1A1B27),
        onBackground         = Color(0xFFE3E1F5),
        surface              = Color(0xFF1A1B27),
        onSurface            = Color(0xFFE3E1F5),
        surfaceVariant       = Color(0xFF46464F),
        onSurfaceVariant     = Color(0xFFC7C5D0),
        outline              = Color(0xFF90909A),
    )
}
