package com.example.uai.design.theme

import androidx.compose.ui.graphics.Color

// Light palette — warm clay/terracotta (Claude-inspired)
val LightPrimary             = Color(0xFFB5533C)
val LightOnPrimary           = Color(0xFFFFFFFF)
val LightPrimaryContainer    = Color(0xFFFFDAD0)
val LightOnPrimaryContainer  = Color(0xFF3B0A02)
val LightSecondary           = Color(0xFF77574D)
val LightOnSecondary         = Color(0xFFFFFFFF)
val LightSecondaryContainer  = Color(0xFFFFDDD5)
val LightOnSecondaryContainer = Color(0xFF2C160F)
val LightBackground          = Color(0xFFFAF9F7)
val LightOnBackground        = Color(0xFF1C1917)
val LightSurface             = Color(0xFFFAF9F7)
val LightOnSurface           = Color(0xFF1C1917)
val LightSurfaceVariant      = Color(0xFFEDE8E1)
val LightOnSurfaceVariant    = Color(0xFF534540)
val LightOutline             = Color(0xFF857369)
val LightOutlineVariant      = Color(0xFFD8C2BB)
val LightError               = Color(0xFFBA1A1A)
val LightOnError             = Color(0xFFFFFFFF)
val LightErrorContainer      = Color(0xFFFFDAD6)
val LightOnErrorContainer    = Color(0xFF410002)

// Dark palette
val DarkPrimary              = Color(0xFFFFB59D)
val DarkOnPrimary            = Color(0xFF5B1608)
val DarkPrimaryContainer     = Color(0xFF8E3B27)
val DarkOnPrimaryContainer   = Color(0xFFFFDAD0)
val DarkSecondary            = Color(0xFFE7BDB3)
val DarkOnSecondary          = Color(0xFF442922)
val DarkSecondaryContainer   = Color(0xFF5D3F37)
val DarkOnSecondaryContainer = Color(0xFFFFDDD5)
val DarkBackground           = Color(0xFF1C1917)
val DarkOnBackground         = Color(0xFFEDE0DC)
val DarkSurface              = Color(0xFF1C1917)
val DarkOnSurface            = Color(0xFFEDE0DC)
val DarkSurfaceVariant       = Color(0xFF534540)
val DarkOnSurfaceVariant     = Color(0xFFD8C2BB)
val DarkOutline              = Color(0xFFA08C86)
val DarkOutlineVariant       = Color(0xFF534540)
val DarkError                = Color(0xFFFFB4AB)
val DarkOnError              = Color(0xFF690005)
val DarkErrorContainer       = Color(0xFF93000A)
val DarkOnErrorContainer     = Color(0xFFFFDAD6)
